# MCP Server Configuration
# This file defines the Model Context Protocol servers that provide tools
# for loan processing business logic
#
# NOTE: Host and port values shown here are defaults for documentation purposes.
# Actual runtime values are read from environment variables:
#   - MCP_SERVER_HOST (default: 0.0.0.0)
#   - MCP_APPLICATION_VERIFICATION_PORT (default: 8010)
#   - MCP_DOCUMENT_PROCESSING_PORT (default: 8011)
#   - MCP_FINANCIAL_CALCULATIONS_PORT (default: 8012)
#   - MCP_TRANSPORT (default: streamable-http)
#
# Each MCP server independently reads these environment variables via
# MCPServerConfig helper to maintain server independence.

servers:
  application_verification:
    host: "localhost"
    port: 8010
    url: "http://localhost:8010/sse"
    description: "Handles identity, address, and employment verification"
    tools:
      - "verify_identity"
      - "verify_address"
      - "check_fraud_indicators"
      - "verify_employment"
      - "get_credit_report"
      - "verify_bank_account"

  document_processing:
    host: "localhost"
    port: 8011
    url: "http://localhost:8011/sse"
    description: "Processes and extracts data from documents"
    tools:
      - "extract_text_from_document"
      - "classify_document_type"
      - "validate_document_format"
      - "extract_structured_data"
      - "convert_document_format"

  financial_calculations:
    host: "localhost"
    port: 8012
    url: "http://localhost:8012/sse"
    description: "Performs financial calculations and risk assessments"
    tools:
      - "calculate_debt_to_income"
      - "calculate_loan_affordability"
      - "calculate_credit_utilization"
      - "calculate_risk_score"
      - "calculate_amortization_schedule"

# Configuration metadata
metadata:
  version: "1.0.0"
  last_updated: "2024-09-24"
  description: "MCP server configuration for loan processing tools"