# MCP Server Configuration
# This file defines the Model Context Protocol servers that provide tools
# for loan processing business logic

servers:
  application_verification:
    host: "localhost"
    port: 8010
    url: "http://localhost:8010/sse"
    description: "Handles identity, address, and employment verification"
    tools:
      - "verify_identity"
      - "verify_address"
      - "check_fraud_indicators"
      - "verify_employment"
      - "get_credit_report"
      - "verify_bank_account"

  document_processing:
    host: "localhost"
    port: 8011
    url: "http://localhost:8011/sse"
    description: "Processes and extracts data from documents"
    tools:
      - "extract_text_from_document"
      - "classify_document_type"
      - "validate_document_format"
      - "extract_structured_data"
      - "convert_document_format"

  financial_calculations:
    host: "localhost"
    port: 8012
    url: "http://localhost:8012/sse"
    description: "Performs financial calculations and risk assessments"
    tools:
      - "calculate_debt_to_income"
      - "calculate_loan_affordability"
      - "calculate_credit_utilization"
      - "calculate_risk_score"
      - "calculate_amortization_schedule"

# Configuration metadata
metadata:
  version: "1.0.0"
  last_updated: "2024-09-24"
  description: "MCP server configuration for loan processing tools"